version: '3.9'

services:
  bin_bag_challenge:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: bin_bag_challenge
    ports: 
      - "8888:8888"
    volumes:
      - ./:/workspace
    environment:
      - PATH="/opt/venv/bin:$PATH"
    command: /bin/bash -c "poetry install && poetry run jupyter lab --ip 0.0.0.0 --allow-root --no-browser"
