version: '3.9'

services:
  bin_bag_challenge:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: bin_bag_challenge
    ports: 
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./data:/workspace/data
    command: /bin/bash -c "jupyter notebook --ip 0.0.0.0 --allow-root --no-browser"
